//go:build ignore

// gen.go reads ../../VERSIONS and regenerates versions.go with const values.
// Usage: go generate ./internal/versions/
package main

import (
	"fmt"
	"os"
	"strings"
)

func main() {
	data, err := os.ReadFile("../../VERSIONS")
	if err != nil {
		fmt.Fprintf(os.Stderr, "cannot read ../../VERSIONS: %v\n", err)
		os.Exit(1)
	}

	vars := map[string]string{}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		vars[strings.TrimSpace(k)] = strings.TrimSpace(v)
	}

	// Map VERSIONS keys → Go constant names.
	entries := []struct{ goName, key string }{
		{"Kopia", "KOPIA"},
		{"GoMajor", "GO_MAJOR"},
		{"NodeMajor", "NODE_MAJOR"},
	}

	var consts []string
	for _, e := range entries {
		v := vars[e.key]
		if v == "" {
			fmt.Fprintf(os.Stderr, "warning: key %s not found in VERSIONS\n", e.key)
			continue
		}
		consts = append(consts, fmt.Sprintf("\t%s = %q", e.goName, v))
	}

	src := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.

package versions

const (
%s
)
`, strings.Join(consts, "\n"))

	if err := os.WriteFile("versions_gen.go", []byte(src), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write versions_gen.go: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("generated versions_gen.go")
}
