package caddy

import (
	"context"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"time"

	"github.com/web-casa/webcasa/internal/config"
	"github.com/web-casa/webcasa/internal/versions"
)

// Manager handles Caddy process lifecycle and configuration reloading
type Manager struct {
	cfg  *config.Config
	mu   sync.Mutex
	proc *os.Process // tracked only when we start Caddy ourselves
}

// NewManager creates a new Caddy manager
func NewManager(cfg *config.Config) *Manager {
	return &Manager{cfg: cfg}
}

// WriteCaddyfile atomically writes a Caddyfile:
//  1. Write to temp file
//  2. Validate with `caddy validate`
//  3. Backup current file
//  4. Rename temp → final
func (m *Manager) WriteCaddyfile(content string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	targetPath := m.cfg.CaddyfilePath
	tmpPath := targetPath + ".tmp"
	backupDir := filepath.Join(m.cfg.DataDir, "backups")

	// 1. Write temp file
	if err := os.WriteFile(tmpPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write temp Caddyfile: %w", err)
	}

	// 2. Validate (skip if caddy binary is not available)
	if _, lookErr := exec.LookPath(m.cfg.CaddyBin); lookErr == nil {
		cmd := exec.Command(m.cfg.CaddyBin, "validate", "--config", tmpPath)
		output, err := cmd.CombinedOutput()
		if err != nil {
			os.Remove(tmpPath)
			return fmt.Errorf("Caddyfile validation failed: %s\n%s", err, string(output))
		}
	} else {
		log.Printf("⚠️  Caddy binary not found (%s), skipping validation", m.cfg.CaddyBin)
	}

	// 3. Backup current file (if exists)
	if _, err := os.Stat(targetPath); err == nil {
		backupName := fmt.Sprintf("Caddyfile.%s.bak", time.Now().Format("20060102-150405"))
		backupPath := filepath.Join(backupDir, backupName)
		data, _ := os.ReadFile(targetPath)
		os.WriteFile(backupPath, data, 0644)

		// Keep only last 10 backups
		m.cleanupBackups(backupDir, 10)
	}

	// 4. Atomic rename
	if err := os.Rename(tmpPath, targetPath); err != nil {
		return fmt.Errorf("failed to rename Caddyfile: %w", err)
	}

	log.Printf("Caddyfile written successfully to %s", targetPath)
	return nil
}

// Reload tells Caddy to reload its configuration
func (m *Manager) Reload() error {
	cmd := exec.Command(m.cfg.CaddyBin, "reload", "--config", m.cfg.CaddyfilePath)
	
	// Force Caddy to use our data dir for certificates, skipping user $HOME permissions
	caddyDataDir := filepath.Join(filepath.Dir(m.cfg.CaddyfilePath), "caddy_data")
	caddyConfigDir := filepath.Join(filepath.Dir(m.cfg.CaddyfilePath), "caddy_config")
	cmd.Env = append(os.Environ(), 
		"XDG_DATA_HOME="+caddyDataDir,
		"XDG_CONFIG_HOME="+caddyConfigDir,
	)

	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("caddy reload failed: %s\n%s", err, string(output))
	}
	log.Println("Caddy reloaded successfully")
	return nil
}

// EnsureCaddyfile creates a minimal valid Caddyfile if one does not exist.
// This allows Caddy to start even before any proxy hosts are configured.
func (m *Manager) EnsureCaddyfile() error {
	if _, err := os.Stat(m.cfg.CaddyfilePath); err == nil {
		return nil // file already exists
	}

	log.Printf("Caddyfile not found at %s, creating default...", m.cfg.CaddyfilePath)

	// Ensure parent directory exists
	os.MkdirAll(filepath.Dir(m.cfg.CaddyfilePath), 0755)

	defaultCaddyfile := fmt.Sprintf(`# ============================================
# Auto-generated by Web.Casa (https://web.casa)
# DO NOT EDIT MANUALLY — changes will be overwritten
# ============================================

{
	admin localhost:2019
	log {
		output file %s/caddy.log {
			roll_size 100MiB
			roll_keep 5
		}
		level INFO
	}
}
`, m.cfg.LogDir)

	if err := os.WriteFile(m.cfg.CaddyfilePath, []byte(defaultCaddyfile), 0644); err != nil {
		return fmt.Errorf("failed to create default Caddyfile: %w", err)
	}

	log.Println("Default Caddyfile created successfully")
	return nil
}

// Start starts the Caddy process
func (m *Manager) Start() error {
	m.mu.Lock()
	defer m.mu.Unlock()

	if m.IsRunning() {
		return fmt.Errorf("caddy is already running")
	}

	// Ensure Caddyfile exists before starting (without lock, already held)
	if _, err := os.Stat(m.cfg.CaddyfilePath); os.IsNotExist(err) {
		log.Println("No Caddyfile found, creating default before starting Caddy...")
		os.MkdirAll(filepath.Dir(m.cfg.CaddyfilePath), 0755)
		defaultCfg := fmt.Sprintf("# Auto-generated by Web.Casa (https://web.casa)\n{\n\tadmin localhost:2019\n\tlog {\n\t\toutput file %s/caddy.log {\n\t\t\troll_size 100MiB\n\t\t\troll_keep 5\n\t\t}\n\t\tlevel INFO\n\t}\n}\n", m.cfg.LogDir)
		if err := os.WriteFile(m.cfg.CaddyfilePath, []byte(defaultCfg), 0644); err != nil {
			return fmt.Errorf("failed to create default Caddyfile: %w", err)
		}
	}

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, m.cfg.CaddyBin, "start", "--config", m.cfg.CaddyfilePath)
	
	// Force Caddy to use our data dir for certificates
	caddyDataDir := filepath.Join(filepath.Dir(m.cfg.CaddyfilePath), "caddy_data")
	caddyConfigDir := filepath.Join(filepath.Dir(m.cfg.CaddyfilePath), "caddy_config")
	cmd.Env = append(os.Environ(), 
		"XDG_DATA_HOME="+caddyDataDir,
		"XDG_CONFIG_HOME="+caddyConfigDir,
	)

	// IMPORTANT: Do NOT use CombinedOutput() here!
	// `caddy start` forks a background daemon (caddy run) that inherits
	// stdout/stderr pipes. CombinedOutput() waits for pipe EOF, which
	// never happens while the daemon is running → blocks forever.
	// Using Run() with nil Stdout/Stderr avoids creating pipes entirely.
	cmd.Stdout = nil
	cmd.Stderr = nil
	if err := cmd.Run(); err != nil {
		if ctx.Err() == context.DeadlineExceeded {
			return fmt.Errorf("caddy start timed out after 15s")
		}
		return fmt.Errorf("caddy start failed: %v", err)
	}
	log.Println("Caddy started successfully")
	return nil
}

// Stop stops the Caddy process
func (m *Manager) Stop() error {
	m.mu.Lock()
	defer m.mu.Unlock()

	cmd := exec.Command(m.cfg.CaddyBin, "stop")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("caddy stop failed: %s\n%s", err, string(output))
	}
	log.Println("Caddy stopped successfully")
	return nil
}

// IsRunning checks if a Caddy process is currently running
func (m *Manager) IsRunning() bool {
	// Try to hit the admin API
	cmd := exec.Command("curl", "-s", "-o", "/dev/null", "-w", "%{http_code}", m.cfg.AdminAPI+"/config/")
	output, err := cmd.Output()
	if err != nil {
		return false
	}
	return strings.TrimSpace(string(output)) == "200"
}

// Status returns the current Caddy status
func (m *Manager) Status() map[string]interface{} {
	running := m.IsRunning()
	status := map[string]interface{}{
		"running":        running,
		"caddy_bin":      m.cfg.CaddyBin,
		"caddyfile_path": m.cfg.CaddyfilePath,
	}

	ver := m.Version()
	if ver != "" {
		status["version"] = ver
	}

	return status
}

// GetCaddyfileContent returns the current Caddyfile content
func (m *Manager) GetCaddyfileContent() (string, error) {
	data, err := os.ReadFile(m.cfg.CaddyfilePath)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// Format formats a Caddyfile string using `caddy fmt`
func (m *Manager) Format(content string) (string, error) {
	cmd := exec.Command(m.cfg.CaddyBin, "fmt", "-")
	cmd.Stdin = strings.NewReader(content)
	output, err := cmd.Output()
	if err != nil {
		return content, fmt.Errorf("caddy fmt failed: %w", err)
	}
	return string(output), nil
}

// Validate validates a Caddyfile string using `caddy validate`
func (m *Manager) Validate(content string) error {
	tmpPath := m.cfg.CaddyfilePath + ".validate.tmp"
	if err := os.WriteFile(tmpPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write temp file: %w", err)
	}
	defer os.Remove(tmpPath)

	cmd := exec.Command(m.cfg.CaddyBin, "validate", "--config", tmpPath)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s", strings.TrimSpace(string(output)))
	}
	return nil
}

// Version returns the current Caddy version string (e.g. "2.11.2").
func (m *Manager) Version() string {
	cmd := exec.Command(m.cfg.CaddyBin, "version")
	output, err := cmd.Output()
	if err != nil {
		return ""
	}
	ver := strings.TrimSpace(string(output))
	if idx := strings.IndexByte(ver, ' '); idx > 0 {
		ver = ver[:idx]
	}
	return strings.TrimPrefix(ver, "v")
}

// LocalPinnedVersion returns the Caddy version compiled into this binary.
func (m *Manager) LocalPinnedVersion() string {
	return versions.Caddy
}

// remoteVersionsURL is the canonical source for the latest pinned versions.
const remoteVersionsURL = "https://raw.githubusercontent.com/web-casa/webcasa/refs/heads/main/VERSIONS"

// LatestPinnedVersion fetches the CADDY version from the upstream VERSIONS file.
// Falls back to the compiled-in constant if the network request fails.
func (m *Manager) LatestPinnedVersion() string {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, remoteVersionsURL, nil)
	if err != nil {
		return versions.Caddy
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil || resp.StatusCode != http.StatusOK {
		return versions.Caddy
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(io.LimitReader(resp.Body, 4096))
	if err != nil {
		return versions.Caddy
	}

	for _, line := range strings.Split(string(body), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "CADDY=") {
			return strings.TrimPrefix(line, "CADDY=")
		}
	}
	return versions.Caddy
}

// Upgrade downloads the given Caddy version (or latest pinned) and replaces the binary.
// If Caddy is running, it is stopped before replacement and restarted after.
func (m *Manager) Upgrade(targetVer string) (string, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if targetVer == "" {
		targetVer = m.LatestPinnedVersion()
	}
	currentVer := m.Version()
	if currentVer == targetVer {
		return currentVer, fmt.Errorf("already running v%s", targetVer)
	}

	goArch := runtime.GOARCH // "amd64" or "arm64"
	url := fmt.Sprintf(
		"https://github.com/caddyserver/caddy/releases/download/v%s/caddy_%s_linux_%s.tar.gz",
		targetVer, targetVer, goArch,
	)

	// Download
	log.Printf("Downloading Caddy v%s from %s", targetVer, url)
	resp, err := http.Get(url)
	if err != nil {
		return currentVer, fmt.Errorf("download failed: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return currentVer, fmt.Errorf("download returned HTTP %d", resp.StatusCode)
	}

	tmpDir, err := os.MkdirTemp("", "caddy-upgrade-*")
	if err != nil {
		return currentVer, fmt.Errorf("create temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	tarPath := filepath.Join(tmpDir, "caddy.tar.gz")
	f, err := os.Create(tarPath)
	if err != nil {
		return currentVer, fmt.Errorf("create temp file: %w", err)
	}
	if _, err := io.Copy(f, resp.Body); err != nil {
		f.Close()
		return currentVer, fmt.Errorf("download write: %w", err)
	}
	f.Close()

	// Extract
	extractCmd := exec.Command("tar", "-xzf", tarPath, "-C", tmpDir, "caddy")
	if out, err := extractCmd.CombinedOutput(); err != nil {
		return currentVer, fmt.Errorf("extract failed: %s %w", string(out), err)
	}

	newBin := filepath.Join(tmpDir, "caddy")
	if _, err := os.Stat(newBin); err != nil {
		return currentVer, fmt.Errorf("caddy binary not found in archive")
	}

	// Stop Caddy if running
	wasRunning := m.IsRunning()
	if wasRunning {
		stopCmd := exec.Command(m.cfg.CaddyBin, "stop")
		stopCmd.CombinedOutput() // best-effort
		log.Println("Stopped Caddy for upgrade")
	}

	// Backup current binary
	caddyBin := m.cfg.CaddyBin
	backupPath := caddyBin + ".bak"
	if _, err := os.Stat(caddyBin); err == nil {
		os.Rename(caddyBin, backupPath)
	}

	// Install new binary
	data, err := os.ReadFile(newBin)
	if err != nil {
		// Rollback
		os.Rename(backupPath, caddyBin)
		return currentVer, fmt.Errorf("read new binary: %w", err)
	}
	if err := os.WriteFile(caddyBin, data, 0755); err != nil {
		os.Rename(backupPath, caddyBin)
		return currentVer, fmt.Errorf("write new binary: %w", err)
	}

	// setcap for privileged ports
	exec.Command("setcap", "cap_net_bind_service=+ep", caddyBin).Run()

	// Restart if was running
	if wasRunning {
		startCmd := exec.Command(caddyBin, "start", "--config", m.cfg.CaddyfilePath)
		caddyDataDir := filepath.Join(filepath.Dir(m.cfg.CaddyfilePath), "caddy_data")
		caddyConfigDir := filepath.Join(filepath.Dir(m.cfg.CaddyfilePath), "caddy_config")
		startCmd.Env = append(os.Environ(),
			"XDG_DATA_HOME="+caddyDataDir,
			"XDG_CONFIG_HOME="+caddyConfigDir,
		)
		startCmd.Stdout = nil
		startCmd.Stderr = nil
		if err := startCmd.Run(); err != nil {
			// Rollback
			log.Printf("Failed to start new Caddy, rolling back: %v", err)
			exec.Command(caddyBin, "stop").Run()
			os.Rename(backupPath, caddyBin)
			exec.Command(caddyBin, "start", "--config", m.cfg.CaddyfilePath).Run()
			return currentVer, fmt.Errorf("new Caddy failed to start, rolled back: %w", err)
		}
		log.Println("Caddy restarted with new version")
	}

	// Clean up backup
	os.Remove(backupPath)

	newVer := m.Version()
	log.Printf("Caddy upgraded: %s → %s", currentVer, newVer)
	return newVer, nil
}

func (m *Manager) cleanupBackups(dir string, keep int) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return
	}

	var backups []os.DirEntry
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), "Caddyfile.") && strings.HasSuffix(e.Name(), ".bak") {
			backups = append(backups, e)
		}
	}

	if len(backups) <= keep {
		return
	}

	// Sort by name (which includes timestamp), oldest first
	for i := 0; i < len(backups)-keep; i++ {
		os.Remove(filepath.Join(dir, backups[i].Name()))
	}
}
